id: P190C5694
initial_creation_type: ocr
source_metadata:
  volumes:
    545632714bdf4d4ea6520c10e4dc3042:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོའི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
